const fs = require('fs');
const settingsJSON = `{"mobile": {"appGap": "10px", "buttonGap": "8px", "fontFamily": "system", "cardPadding": "24px", "inputHeight": "40px", "baseFontSize": "12px", "codeFontSize": "12px", "modalPadding": "18px", "panelPadding": "10px", "stackCardGap": "7px", "answerPadding": "0px", "questionAlign": "center", "answerFontSize": "13px", "baseLineHeight": "1.23", "buttonFontSize": "14px", "cardContentGap": "16px", "codeLineHeight": "1.17", "appWidthPercent": "100", "cardBorderWidth": "1px", "questionPadding": "2px", "answerFontFamily": "system", "answerFontWeight": "300", "answerLineHeight": "1.58", "appHeightPercent": "100", "cardCornerRadius": "14px", "cardWidthPercent": "96", "inputCornerRadius": "8px", "modalWidthPercent": "60", "panelCornerRadius": "14px", "stackCardFontSize": "13px", "actionButtonHeight": "42px", "buttonCornerRadius": "8px", "questionFontFamily": "system", "questionFontWeight": "700", "questionLineHeight": "1.18", "replayButtonHeight": "30px", "questionFillPercent": "51", "questionMaxFontSize": "20px", "rawMarkdownFontSize": "16px", "stackCardLineHeight": "1.28", "toolbarButtonHeight": "38px", "cardMaxHeightPercent": "80", "questionVerticalAlign": "center", "sidePanelWidthPercent": "16", "visualMaxWidthPercent": "90", "markdownBoxHeightPercent": "30"}, "desktop": {"appGap": "10px", "buttonGap": "8px", "fontFamily": "system", "cardPadding": "24px", "inputHeight": "40px", "baseFontSize": "18px", "codeFontSize": "12px", "modalPadding": "18px", "panelPadding": "10px", "stackCardGap": "7px", "answerPadding": "0px", "questionAlign": "center", "answerFontSize": "23px", "baseLineHeight": "1.58", "buttonFontSize": "14px", "cardContentGap": "16px", "codeLineHeight": "1.55", "appWidthPercent": "100", "cardBorderWidth": "1px", "questionPadding": "2px", "answerFontFamily": "system", "answerFontWeight": "400", "answerLineHeight": "1.58", "appHeightPercent": "100", "cardCornerRadius": "14px", "cardWidthPercent": "100", "inputCornerRadius": "8px", "modalWidthPercent": "60", "panelCornerRadius": "14px", "stackCardFontSize": "13px", "actionButtonHeight": "42px", "buttonCornerRadius": "8px", "questionFontFamily": "system", "questionFontWeight": "700", "questionLineHeight": "1.18", "replayButtonHeight": "30px", "questionFillPercent": "58", "questionMaxFontSize": "19px", "rawMarkdownFontSize": "18px", "stackCardLineHeight": "1.28", "toolbarButtonHeight": "38px", "cardMaxHeightPercent": "84", "questionVerticalAlign": "center", "sidePanelWidthPercent": "6", "visualMaxWidthPercent": "50", "markdownBoxHeightPercent": "30"}, "version": 2}`;

let code = fs.readFileSync('app.js', 'utf8');

// Find the styleDefaults declaration and replace its body
code = code.replace(/const styleDefaults = \{[\s\S]*?\n\};/, 'const styleDefaults = ' + settingsJSON + ';');

fs.writeFileSync('app.js', code);
